### ISSUE TITLE
Scoped router

### ISSUE THREAD

**Issue by susilolab** [igeligel/vuex-feature-scoped-structure#3]
should i scope the router too?. what if module contain create, read, update delete?. thanks

**Comment by thewebuiguy** [comment]
The vue-router is a singelton object, so its a bit difficult to scope it into a specific module, you will probably end up using something such as create children on the router but with no way to persist them will lose your place in the application, its one failing of vue router.

**Comment by susilolab** [comment]
> The vue-router is a singelton object, so its a bit difficult to scope it into a specific module, you will probably end up using something such as create children on the router but with no way to persist them will lose your place in the application, its one failing of vue router.

thanks
